# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  #schedule:
  # 每天的UTC 时间的1.30 执行一次
   # - cron:  '30 1 0 * *'
permissions:
  contents: read|write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bs4
        pip install requests
        pip install lxml
    - name: run unity_download
      run: |
        python unity_download.py
    - name: run decode_html
      run: |
        python decode_html.py
    - name: publish markdown
      #id: publish markdown
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ github.token }}
        files: |
          download.html
          download-archive-3.md
          download-archive-4.md
          download-archive-5.md
          download-archive-2017.md
          download-archive-2018.md
          download-archive-2019.md
          download-archive-2020.md
          download-archive-2021.md
          download-archive-2022.md
        
